"""Generate docs/phase0-convergence.md: solver error vs grid spacing, observed order."""

from pathlib import Path

import numpy as np

from atomsim.analytic.hydrogen import energy
from atomsim.numerics.radial_solver import solve_radial

CASES = [
    ("3D harmonic oscillator (l=0, E=1.5)", lambda r: 0.5 * r**2, 1.5, 0, 12.0,
     [600, 1200, 2400, 4800]),
    ("Hydrogen 1s (E=-0.5)", lambda r: -1.0 / r, energy(1).value, 0, 60.0,
     [3000, 6000, 12000, 24000]),
    ("Hydrogen 2p (E=-0.125)", lambda r: -1.0 / r, energy(2).value, 1, 100.0,
     [3000, 6000, 12000, 24000]),
]


def main() -> None:
    lines = [
        "# Phase 0 convergence study",
        "",
        "3-point finite-difference radial solver, uniform grid. Generated by",
        "`scripts/convergence_study.py` — regenerate after any solver change.",
        "",
    ]
    for name, pot, exact, l, r_max, n_list in CASES:
        header = r"| N (grid points) | h (bohr) | \|E_num - E_exact\| (hartree) | observed order |"
        lines += [f"## {name}", "", header, "|---|---|---|---|"]
        prev = None
        for n in n_list:
            e = solve_radial(pot, l=l, r_max=r_max, n_points=n, n_states=1).energies[0].value
            err = abs(e - exact)
            order = f"{np.log2(prev / err):.2f}" if prev else "—"
            lines.append(f"| {n} | {r_max / (n + 1):.2e} | {err:.3e} | {order} |")
            prev = err
        lines.append("")
    lines += [
        "**Reading the results:** all three cases show clean O(h^2) convergence,"
        " including the Coulomb s state. The scheme solves for u = r R(r), which is"
        " smooth at the origin for the Coulomb potential, so second order is expected"
        " here rather than fortunate; cusp-related order reduction was not observed at"
        " these resolutions. Every solver energy can carry a grid-halving error estimate"
        " via `solve_radial_with_error`.",
        "",
    ]
    out = Path(__file__).resolve().parents[1] / "docs" / "phase0-convergence.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
