"""Generate web/src/lib/luts.ts from matplotlib colormaps.

Single color authority: server thumbnails (matplotlib) and the browser client
read the same 256-entry tables, so a density looks identical in a thumbnail,
the cross-section canvas and the 3D cloud. Re-run after a matplotlib upgrade.
"""

from pathlib import Path

import matplotlib
import numpy as np

OUT = Path(__file__).resolve().parents[1] / "web" / "src" / "lib" / "luts.ts"


def rows(name: str) -> str:
    cmap = matplotlib.colormaps[name]
    rgb = (np.asarray(cmap(np.linspace(0.0, 1.0, 256)))[:, :3] * 255).round().astype(int)
    return ",\n".join(f"  [{r}, {g}, {b}]" for r, g, b in rgb)


TEMPLATE = """\
// GENERATED by scripts/gen_luts.py from matplotlib {version} - do not edit by hand.
// Single color authority: server thumbnails (matplotlib) and this client LUT
// come from the same colormaps, so densities look identical everywhere.

export type Lut = ReadonlyArray<readonly [number, number, number]>;

export const INFERNO: Lut = [
{inferno},
];

export const RDBU_R: Lut = [
{rdbu},
];
"""

OUT.write_text(
    TEMPLATE.format(version=matplotlib.__version__, inferno=rows("inferno"),
                    rdbu=rows("RdBu_r")),
    encoding="utf-8", newline="\n",
)
print(f"wrote {OUT}")
